### Bagging

A quick little demo of the bagging operations

In [1]:
import numpy as np

In [2]:
n=15

# random response vector
y = np.round(np.random.normal(size=n), 3)

# add a little noise
yhat = np.round(y + .01* np.random.normal(size=n), 3)


In [3]:
# Choose a random bag of data, by sampling with replacement
bag = np.random.choice(range(n), replace=True, size=n)
bag

array([12,  0, 14,  7,  0,  2,  5,  6,  6, 11,  2,  2,  1,  3,  2])

In [4]:
# list the out-of-bag (OOB) points 
oob = list(set(range(n)) - set(bag))
oob = np.array(oob)
oob

array([ 4,  8,  9, 10, 13])

In [5]:
# What fraction of points are OOB? Should be about 1 - (1 - 1/e)
len(oob)/len(bag), 1-(1 - 1/np.exp(1))

(0.3333333333333333, 0.36787944117144233)

In [6]:
# Calculate the residuals on the OOB points
y[oob] - yhat[oob]

array([-0.02 , -0.002,  0.   ,  0.01 , -0.007])